name: Playwright Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ebf-pod-ubuntu-2004@${{ github.run_id }}-e2e-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Install xvfb for testing extension with headed mode
        run: sudo apt-get install xvfb

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Execute tests
        run: xvfb-run --auto-servernum npx playwright test